// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXEpnkhVJBjnrYOWPe49-L-p3LzEgXUsQ',
    appId: '1:638248770028:web:a8a9a5d98127462e92c8c9',
    messagingSenderId: '638248770028',
    projectId: 'chat-application-3651f',
    authDomain: 'chat-application-3651f.firebaseapp.com',
    storageBucket: 'chat-application-3651f.firebasestorage.app',
    measurementId: 'G-YNLL3E0E15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ-KWq912tMFjZipjEDd1kp0YP6jltMQE',
    appId: '1:638248770028:android:2d31638510e6e74c92c8c9',
    messagingSenderId: '638248770028',
    projectId: 'chat-application-3651f',
    storageBucket: 'chat-application-3651f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtAtBx5lzzW7iktx3HwIT7SsNpvrF__F4',
    appId: '1:638248770028:ios:3e3222fac3ad023d92c8c9',
    messagingSenderId: '638248770028',
    projectId: 'chat-application-3651f',
    storageBucket: 'chat-application-3651f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtAtBx5lzzW7iktx3HwIT7SsNpvrF__F4',
    appId: '1:638248770028:ios:3e3222fac3ad023d92c8c9',
    messagingSenderId: '638248770028',
    projectId: 'chat-application-3651f',
    storageBucket: 'chat-application-3651f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXEpnkhVJBjnrYOWPe49-L-p3LzEgXUsQ',
    appId: '1:638248770028:web:fe218307e8eadd6492c8c9',
    messagingSenderId: '638248770028',
    projectId: 'chat-application-3651f',
    authDomain: 'chat-application-3651f.firebaseapp.com',
    storageBucket: 'chat-application-3651f.firebasestorage.app',
    measurementId: 'G-DMRSR8TQ3G',
  );
}
